inputs_def:
  - handle: texts
    description: Input
    json_schema:
      type: array
      items:
        type: string
    value:
      []
  - handle: timeout
    json_schema:
      type: number
      exclusiveMinimum: 0
    value:
    nullable: true
  - handle: llm
    json_schema:
      ui:options:
        title: Model
      ui:widget: llm::model
    value:
      model: deepseek-chat
      temperature: 1
      top_p: 0.8
      max_tokens: 4096
  - handle: source
    json_schema:
      enum:
        - en
        - cn
        - ja
        - fr
        - ru
        - de
      ui:options:
        labels:
          - English
          - 中文
          - 日本語
          - Français
          - Русский
          - Deutsch
    nullable: false
  - handle: target
    json_schema:
      enum:
        - en
        - cn
        - ja
        - fr
        - ru
        - de
      ui:options:
        labels:
          - English
          - 中文
          - 日本語
          - Français
          - Русский
          - Deutsch
    nullable: false
  - handle: group_max_tokens
    json_schema:
      type: integer
      exclusiveMinimum: 0
    value: 1000
outputs_def:
  - handle: texts
    description: Output
    json_schema:
      type: array
      items:
        type: string
ui:
  default_width: 525.2577585195525
executor:
  name: python
  options:
    entry: __init__.py
    spawn: false
title: Translate texts list
icon: ":carbon:list-bulleted:"
private: true
