inputs_def:
  - handle: texts
    description: List of text strings to be translated
    json_schema:
      type: array
      items:
        type: string
    value:
      []
  - handle: timeout
    description: Request timeout in seconds (optional)
    json_schema:
      type: number
      exclusiveMinimum: 0
    value:
    nullable: true
  - handle: llm
    description: Language model configuration for translation
    json_schema:
      ui:options:
        title: Model
      ui:widget: llm::model
    value:
      model: deepseek-chat
      temperature: 1
      top_p: 0.8
      max_tokens: 4096
  - handle: source
    description: Source language code
    json_schema:
      enum:
        - en
        - cn
        - ja
        - fr
        - ru
        - de
      ui:options:
        labels:
          - English
          - 中文
          - 日本語
          - Français
          - Русский
          - Deutsch
    nullable: false
  - handle: target
    description: Target language code for translation
    json_schema:
      enum:
        - en
        - cn
        - ja
        - fr
        - ru
        - de
      ui:options:
        labels:
          - English
          - 中文
          - 日本語
          - Français
          - Русский
          - Deutsch
    nullable: false
  - handle: group_max_tokens
    description: Maximum tokens per translation group
    json_schema:
      type: integer
      exclusiveMinimum: 0
    value: 1000
outputs_def:
  - handle: texts
    description: List of translated text strings
    json_schema:
      type: array
      items:
        type: string
ui:
  default_width: 525.2577585195525
executor:
  name: python
  options:
    entry: __init__.py
    spawn: false
title: Translate texts list
description: "Translates a list of text strings from source language to target
  language using AI models"
icon: ":carbon:list-bulleted:"
private: true
